### ISSUE TITLE
Erro versão de leiaute da NF-e utilizada não é mais válida

### ISSUE THREAD

**Issue by thiagoreis** [eNotasGW/php-client-v2#4]
Todas as notas geradas hoje 02/08/2018,  estão sendo negadas com o seguinte erro:
"595 - Rejeição: A versão do leiaute da NF-e utilizada não é mais válida"
estou usando a última versão do php-client-v2 e até  o dia 30/07/2018(quando a última nota foi autorizada) estava tudo funcionando. 
alguém sabe o que pode ser?
foi feito alguma alteração na API?

**Comment by otavioreis** [comment]
Boa tarde Tiago, tudo bem? 

  A princípio não houve qualquer alteração na biblioteca. Você pode entrar em contato diretamente com o nosso suporte, através do ambiente do eNotas Gateway, clicando no balão (situado no canto inferior direito - veja na imagem abaixo), pois assim será aberto um chat diretamente com um especialista para resolver o seu problema.

![chat_enotas](https://user-images.githubusercontent.com/12715245/43596717-7d806836-9656-11e8-98bd-bd8d8ddb044a.gif)

Atenciosamente,
Otávio A. Reis

**Comment by thiagoreis** [comment]
Opa @otavioreis! Vou entrar em contato através do chat. Obrigado!

**Comment by thiagoreis** [comment]
Infelizmente no atendimento do Chat perguntam qual o problema e depois não respondem mais. 
Aparentemente o erro "_595 - Rejeição: A versão do leiaute da NF-e utilizada não é mais válida_" é por causa da desativação da versão 3.10 da NFe que aconteceu no dia 01/08/2018.  
O php-client-v2 não está adaptado para a versão 4.0 da NFe?

**Comment by otavioreis** [comment]
Thiago, 

  Na segunda-feira eu pedi para o pessoal do atendimento dar prioridade no seu caso, inclusive me informaram que neste mesmo dia entraram em contato com vocês. Eu entendo a sua frustração, mas gostaria de lembrar que o gitHub é um canal mais técnico, não fazendo parte dos nossos canais de atendimento e, por isso, não temos pessoas dedicadas para responder aqui.

  Como queremos resolver o seu caso da forma mais satisfatória possível, se ainda estiver precisando de alguma coisa, por favor, basta entrar em contato diretamente com o pessoal do atendimento.

http://atendimento.enotas.com.br

Atenciosamente,
Otávio A. Reis

**Comment by barbaralegnani** [comment]
Oi, Thiago!

Sua demanda foi tratada como prioritária, e **está resolvida**, correto?

Esse contexto se deu porque seu caso trouxe um novo cenário que ainda não tínhamos encontrado até aquele momento.

No dia da virada da NFe 4.0, 02/08, estávamos adequados com o novo leiaute. Porém, na SEFAZ/PE faltava homologar alguns detalhes.

Fazer homologações na SEFAZ pode ser um trabalho árduo, devido a um grande volume de detalhes. Imagino que você saiba disso, né? :/

De qualquer forma, sabemos que nosso papel é sempre resolvermos os problemas o mais rápido possível, considerando que precisam de uma análise bem aprofundada e de alguns testes.

Se desejar tratar qualquer assunto adicional à esta mensagem, por gentileza, me informe um dia/hora e telefone de contato. Ou nos envie uma mensagem em nossa nova Central de Atendimento.

Terei prazer em auxiliá-lo no que for possível.

Bárbara,
Coordenadora de Atendimento da Equipe eNotas.

**Comment by thiagoreis** [comment]
Olá @barbaralegnani !
sim, foi resolvida :) 
Agradeço o empenho da equipe!
