### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by matheusfaustino** [eNotasGW/php-client-v2#5]
Poderiam adicionar essa lib para poder ser instalado via composer, por favor? É a unica coisa que me impede de utilizar a lib de vocês em produção. 

Agradeço

**Comment by EricRibeiro** [comment]
A lib pode ser instalada através do composer com o comando: `composer require enotas/php-client-v2`.

**Comment by matheusfaustino** [comment]
Muito obrigado @EricRibeiro
